In [70]:
import matplotlib.pyplot as pl
import numpy as np
import pandas as pd
from functions.multi_gradient_descent import *

In [71]:
file = "./data from book/BrainCancer.csv"
data = pd.read_csv(file)
data.head()

Unnamed: 0     sex   diagnosis             loc  ki    gtv stereo  status  \
0           1  Female  Meningioma  Infratentorial  90   6.11    SRS       0   
1           2    Male   HG glioma  Supratentorial  90  19.35    SRT       1   
2           3  Female  Meningioma  Infratentorial  70   7.95    SRS       0   
3           4  Female   LG glioma  Supratentorial  80   7.61    SRT       1   
4           5    Male   HG glioma  Supratentorial  90   5.06    SRT       1   

    time  
0  57.64  
1   8.98  
2  26.46  
3  47.80  
4   6.30

In [72]:
ls = []
leadger = []
def categorical_data(x):
    if x not in ls:
        ls.append(x)
    return ls.index(x)

data['diagnosis'] = data['diagnosis'].apply(categorical_data)
leadger.append(ls)
ls =[]
data['loc'] = data['loc'].apply(categorical_data)
leadger.append(ls)
ls =[]
data['stereo'] = data['stereo'].apply(categorical_data)
leadger.append(ls)
ls =[]
data['sex'] = data['sex'].apply(categorical_data)
leadger.append(ls)
ls =[]
print(leadger)
data
x_data = np.array(data[['sex','diagnosis','loc','ki','gtv','stereo']])
y_data = np.array(data['status'])
print(x_data)
print(y_data)

[['Meningioma', 'HG glioma', 'LG glioma', nan, 'Other'], ['Infratentorial', 'Supratentorial'], ['SRS', 'SRT'], ['Female', 'Male']]
[[0.000e+00 0.000e+00 0.000e+00 9.000e+01 6.110e+00 0.000e+00]
 [1.000e+00 1.000e+00 1.000e+00 9.000e+01 1.935e+01 1.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 7.000e+01 7.950e+00 0.000e+00]
 [0.000e+00 2.000e+00 1.000e+00 8.000e+01 7.610e+00 1.000e+00]
 [1.000e+00 1.000e+00 1.000e+00 9.000e+01 5.060e+00 1.000e+00]
 [0.000e+00 0.000e+00 1.000e+00 8.000e+01 4.820e+00 0.000e+00]
 [1.000e+00 0.000e+00 1.000e+00 8.000e+01 3.190e+00 1.000e+00]
 [1.000e+00 2.000e+00 1.000e+00 8.000e+01 1.237e+01 1.000e+00]
 [0.000e+00 0.000e+00 1.000e+00 7.000e+01 1.216e+01 1.000e+00]
 [1.000e+00 1.000e+00 1.000e+00 1.000e+02 2.530e+00 1.000e+00]
 [1.000e+00 2.000e+00 1.000e+00 8.000e+01 1.400e-01 1.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 9.000e+01 6.540e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 9.000e+01 6.300e-01 0.000e+00]
 [1.000e+00 3.000e+00 1.000e+00 9.000e+01 6.380e+0

In [73]:
x_data = feature_scaling(x_data)
y_data = feature_scaling(y_data)