In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl

In [3]:
data = pd.read_csv("./data from book/Credit.csv")


x_data = np.array(data[["Limit","Rating","Cards","Age","Education"]])

y_data = np.array(data["Income"])
x_test = x_data[300:400]
y_test = y_data[300:400]
x_data = x_data[0:300]
y_data = y_data[0:300]
sample_size = x_data.shape[0]
test_size = x_test.shape[0]

x_data

array([[3606,  283,    2,   34,   11],
       [6645,  483,    3,   82,   15],
       [7075,  514,    4,   71,   11],
       ...,
       [4381,  321,    3,   74,   17],
       [2672,  204,    1,   70,   18],
       [5051,  372,    3,   76,   11]], dtype=int64)

In [4]:
def min__j(x_data,y_data,w,b):
    j= 0
    for i in range(x_data.shape[0]):
        j+=(np.dot(x_data[i],w)+b- (y_data[i]))**2
    ghj = (2*x_data.shape[0])
    return j/ghj

In [5]:

def gradient(x_data,y_data, w, b):
    j_i = np.zeros(w.shape[0])
    j_j = 0
    m = x_data.shape[0]
    for i in range(x_data.shape[0]):
        k = (np.dot(x_data[i],w)+b- (y_data[i]))
        for gb in range(w.shape[0]): 
            j_i[gb] += (k*x_data[i][gb])
        
        j_j += k
     
    grad = [1/m * j_i, 1/m * j_j]
    return grad

In [6]:
def gradient_descent(x_data,y_data,w,b):
    dist = 0.00000000006
    hist =[]
    count =0
    for i in range(50000):
        count +=1
        dj_dw,dj_db =  gradient(x_data,y_data,w,b)

    
        w = w-(dist*dj_dw)
        b = b-(dist*dj_db)

        if i%10==0:
            print(w,b,"-------------------------------- j: ",min__j(x_data,y_data,w,b),"dj_dw: ",dj_dw,"dj_db: ",dj_db)
      
    return w,b


In [7]:
def predict_graph(x_data,w,b):
    # pred = np.zeros([x_data.shape[0],])
    pred = np.zeros([x_data.shape[0]])
    for i in range(test_size):
        pred[i] = np.dot(x_data[i],w) +b
    return pred

In [8]:
# w = np.zeros([5])
w = np.zeros(x_data.shape[1])

b=0
per_w,per_b = gradient_descent(x_data,y_data,w,b)
print(per_w, per_b)

[1.57270023e-05 1.15576856e-06 8.07927620e-09 1.49630784e-07
 3.49602264e-08] 2.643263600000001e-09 -------------------------------- j:  1537.6955760558096 dj_dw:  [-2.62116704e+05 -1.92628093e+04 -1.34654603e+02 -2.49384639e+03
 -5.82670440e+02] dj_db:  -44.05439333333335
[1.71624737e-04 1.26123384e-05 8.81363403e-08 1.63264647e-06
 3.81375298e-07] 2.883550670012444e-08 -------------------------------- j:  1496.9977131086005 dj_dw:  [-2.57968185e+05 -1.89571296e+04 -1.32430538e+02 -2.45366330e+03
 -5.73035339e+02] dj_db:  -43.32766910027594
[3.25055080e-04 2.38871009e-05 1.66870609e-07 3.09176268e-06
 7.22059754e-07] 5.4595520021568106e-08 -------------------------------- j:  1457.5779256205367 dj_dw:  [-2.53885325e+05 -1.86562880e+04 -1.30241674e+02 -2.41411620e+03
 -5.63552735e+02] dj_db:  -42.61244692130432
[4.76057083e-04 3.49829335e-05 2.44303020e-07 4.52735767e-06
 1.05710429e-06] 7.993014457787902e-08 -------------------------------- j:  1419.3960769139271 dj_dw:  [-2.49867086e

In [9]:
def show_predictions(x_test,y_test,per_w,per_b):
    print(per_w,per_b)
    pred = predict_graph(x_test,per_w,per_b)
    print(" Limit","Rating","Cards","Age","Education")
    for i in range(test_size):
        print(x_test[i],"       ",round(pred[i],3),y_test[i]) 


show_predictions(x_test,y_test,per_w,per_b)


[ 9.87821432e-03  5.75024128e-04 -1.22974388e-05 -3.91964782e-05
 -5.53208037e-05] -3.8527561800834764e-06
 Limit Rating Cards Age Education
[4632  355    1   50   17]         45.957 21.786
[3526  289    3   38    7]         34.995 31.335
[4964  365    1   46   13]         49.243 59.855
[4970  352    1   79   11]         49.293 44.061
[7506  536    2   64   13]         74.451 82.706
[1924  165    2   50   14]         19.098 24.46
[3762  287    3   80    8]         37.323 45.12
[3874  298    3   41   14]         38.437 75.406
[4640  332    2   33    6]         46.024 14.956
[7010  494    3   34   18]         69.528 75.257
[4891  369    1   52   16]         48.524 33.694
[5429  396    3   57   15]         53.853 23.375
[5227  386    6   63   11]         51.852 27.825
[7685  534    2   75   18]         76.217 92.386
[9272  656    2   69   14]         91.965 115.52
[3907  296    3   43   16]         38.762 14.479
[7306  522    2   57   14]         72.467 52.179
[4712  340    2   71   16]  

In [10]:
def accuracy(x_test,y_test,w,b,):
    pred = predict_graph(x_test,w,b)
    t =np.sum(y_test)
    k = np.sum(pred)
    error = abs(k-t)/t 
    error *= 100
    return error

In [11]:
print(per_w,per_b)

[ 9.87821432e-03  5.75024128e-04 -1.22974388e-05 -3.91964782e-05
 -5.53208037e-05] -3.8527561800834764e-06


In [12]:
print(accuracy(x_test, y_test,per_w,per_b))

3.0158814720447626
