In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl
import math

In [49]:
data = pd.read_csv("./data from book/Credit.csv")


x_data = np.array(data[["Limit","Rating","Cards","Age","Education"]])

y_data = np.array(data["Income"])
x_test = x_data[300:400]
y_test = y_data[300:400]
x_data = x_data[0:300]
y_data = y_data[0:300]
sample_size = x_data.shape[0]
test_size = x_test.shape[0]

x_data

array([[3606,  283,    2,   34,   11],
       [6645,  483,    3,   82,   15],
       [7075,  514,    4,   71,   11],
       ...,
       [4381,  321,    3,   74,   17],
       [2672,  204,    1,   70,   18],
       [5051,  372,    3,   76,   11]], dtype=int64)

In [50]:
def min__j(x_data,y_data,w,b):
    j= 0
    for i in range(x_data.shape[0]):
        j+=(np.dot(x_data[i],w)+b- (y_data[i]))**2
    ghj = (2*x_data.shape[0])
    return j/ghj

In [51]:

def gradient(x_data,y_data, w, b):
    j_i = np.zeros(w.shape[0])
    j_j = 0
    m = x_data.shape[0]
    for i in range(x_data.shape[0]):
        k = (np.dot(x_data[i],w)+b- (y_data[i]))
        if(math.isnan(k)==True):
            print("k is NA")
        for gb in range(w.shape[0]): 
            j_i[gb] += (k*x_data[i][gb])
        
        j_j += k
     
    grad = [1/m * j_i, 1/m * j_j]
    return grad

In [52]:
def gradient_descent(x_data,y_data,w,b):
    dist = 0.0006
    hist =[]
    count =0
    iter = 10
    for i in range(iter):
        count +=1
        dj_dw,dj_db =  gradient(x_data,y_data,w,b)

    
        w = w-(dist*dj_dw)
        b = b-(dist*dj_db)

        if i ==iter-1 or i==iter/4 or i%1000 ==0:
            print(w,b,"-------------------------------- j: ",min__j(x_data,y_data,w,b),"dj_dw: ",dj_dw,"dj_db: ",dj_db)
      
    return w,b


In [53]:
def predict_graph(x_data,w,b):
    # pred = np.zeros([x_data.shape[0],])
    pred = np.zeros([x_data.shape[0]])
    for i in range(test_size):
        pred[i] = np.dot(x_data[i],w) +b
    return pred

In [54]:
# w = np.zeros([5])
w = np.zeros(x_data.shape[1])

b=0
per_w,per_b = gradient_descent(x_data,y_data,w,b)
print(per_w, per_b)

[1.57270023e-04 1.15576856e-05 8.07927620e-08 1.49630784e-06
 3.49602264e-07] 2.6432636000000012e-08 -------------------------------- j:  1500.7179366534074 dj_dw:  [-2.62116704e+05 -1.92628093e+04 -1.34654603e+02 -2.49384639e+03
 -5.82670440e+02] dj_db:  -44.05439333333335
[9.86806607e-03 6.96489831e-04 1.76598188e-06 6.85364039e-05
 7.24168542e-06] 6.102612217247726e-07 -------------------------------- j:  241.74715053472178 dj_dw:  [-4.26100832 50.6711776   5.8649152  44.97357887 26.08910506] dj_db:  1.861117665363911
[9.86870205e-03 6.88889393e-04 8.86277820e-07 6.17910329e-05
 3.32845315e-06] 3.3110307087752276e-07 -------------------------------- j:  241.7463516259035 dj_dw:  [-4.23343524 50.66693961  5.86446624 44.96459615 26.08729869] dj_db:  1.860988980574805
[ 9.87060652e-03  6.66093464e-04 -1.75241893e-06  4.15632094e-05
 -8.40956871e-06] -5.062518507546023e-07 -------------------------------- j:  241.74395631267902 dj_dw:  [-4.2312811  50.64829512  5.8630766  44.93687706 26

In [55]:
def show_predictions(x_test,y_test,per_w,per_b):
    print(per_w,per_b)
    pred = predict_graph(x_test,per_w,per_b)
    print(" Limit","Rating","Cards","Age","Education")
    for i in range(test_size):
        print(x_test[i],"       ",round(pred[i],3),y_test[i]) 


show_predictions(x_test,y_test,per_w,per_b)


[ 9.87821432e-03  5.75024094e-04 -1.22974412e-05 -3.91965280e-05
 -5.53208137e-05] -3.852756898743193e-06
 Limit Rating Cards Age Education
[4632  355    1   50   17]         45.957 21.786
[3526  289    3   38    7]         34.995 31.335
[4964  365    1   46   13]         49.243 59.855
[4970  352    1   79   11]         49.293 44.061
[7506  536    2   64   13]         74.451 82.706
[1924  165    2   50   14]         19.098 24.46
[3762  287    3   80    8]         37.323 45.12
[3874  298    3   41   14]         38.437 75.406
[4640  332    2   33    6]         46.024 14.956
[7010  494    3   34   18]         69.528 75.257
[4891  369    1   52   16]         48.524 33.694
[5429  396    3   57   15]         53.853 23.375
[5227  386    6   63   11]         51.852 27.825
[7685  534    2   75   18]         76.217 92.386
[9272  656    2   69   14]         91.965 115.52
[3907  296    3   43   16]         38.762 14.479
[7306  522    2   57   14]         72.467 52.179
[4712  340    2   71   16]   

In [56]:
def accuracy(x_test,y_test,w,b,):
    pred = predict_graph(x_test,w,b)
    error = 0
    for i in range(pred.shape[0]):
        error += abs(y_test[i] - pred[i])/y_test[i]

    # t =np.sum(y_test)
    # k = np.sum(pred)
    error /= y_test.shape[0]  
    error *= 100
    return error

In [57]:
print(per_w,per_b)

[ 9.87821432e-03  5.75024094e-04 -1.22974412e-05 -3.91965280e-05
 -5.53208137e-05] -3.852756898743193e-06


In [58]:
print(accuracy(x_test, y_test,per_w,per_b))

61.37759959778014
