In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl

In [64]:
data = pd.read_csv("./data from book/Credit.csv")
# data = data[[
# data = np.array(data)
x_data = np.array(data[["Limit","Rating","Cards","Age","Education"]])
y_data = np.array(data["Income"])
x_test = x_data[300:400]
y_test = y_data[300:400]
x_data = x_data[0:300]
y_data = y_data[0:300]
sample_size = x_data.shape[0]
test_size = x_test.shape[0]
x_data

array([[3606,  283,    2,   34,   11],
       [6645,  483,    3,   82,   15],
       [7075,  514,    4,   71,   11],
       ...,
       [4381,  321,    3,   74,   17],
       [2672,  204,    1,   70,   18],
       [5051,  372,    3,   76,   11]], dtype=int64)

In [65]:
def min__j(x_data,y_data,w,b):
    j= 0
    for i in range(x_data.shape[0]):
        j+=(np.dot(x_data[i],w)+b- (y_data[i]))**2
    ghj = (2*x_data.shape[0])
    return j/ghj

In [66]:

def gradient(x_data,y_data, w, b):
    j_i = 0
    j_j = 0
    m = data.shape[0]
    for i in range(x_data.shape[0]):
        k = (np.dot(x_data[i],w)+b- (y_data[i]))
        j_i += k*np.sum(x_data[i])
        j_j += k
        # if k > 1000000000:
        #     break
    grad = [1/m * j_i, 1/m * j_j]
    return grad

In [67]:
def gradient_descent(x_data,y_data,w,b):
    dist = 0.00000000006
    hist =[]
    count =0
    for i in range(50000):
        count +=1
        dj_dw,dj_db =  gradient(x_data,y_data,w,b)

        w = w-(dist*dj_dw)
        b = b-(dist*dj_db)

        # printing
        if i%10==0:
            print(w,b,"-------------------------------- j: ",min__j(x_data,y_data,w,b),"dj_dw: ",dj_dw,"dj_db: ",dj_db)
        # hist.append([w,b])
        # p =False
        # if len(hist)%5==0:
        #     diff =[]
        #     for k in range(4):
        #         diff.append([abs(hist[k][0]-hist[k+1][0]),abs(hist[k][1]-hist[k+1][1])])
        #     for j in diff:
        #         # print("--------------------------------",diff)
        #         if j[0]<0.00005 and j[1]<0.00005:
        #             p=True
        #         else:
        #             p=False
        #             break
        #     hist = []
        #     diff = []
        # if p==True:
        #     print("breaks",count)
        #     break
    return w,b


In [68]:
def predict_graph(x_data,w,b):
    # pred = np.zeros([x_data.shape[0],])
    pred = np.zeros([x_data.shape[0]])
    for i in range(test_size):
        pred[i] = np.dot(x_data[i],w) +b
    return pred

In [69]:
w = np.zeros([5])
b=0
per_w,per_b = gradient_descent(x_data,y_data,w,b)
print(per_w, per_b)

[1.28065808e-05 1.28065808e-05 1.28065808e-05 1.28065808e-05
 1.28065808e-05] 1.9824477000000004e-09 -------------------------------- j:  1538.1951634123645 dj_dw:  -213443.01380999995 dj_db:  -33.04079500000001
[0.00013989 0.00013989 0.00013989 0.00013989 0.00013989] 2.164760929734533e-08 -------------------------------- j:  1502.3313900796475 dj_dw:  -210467.20484164404 dj_db:  -32.55903563718177
[0.0002652 0.0002652 0.0002652 0.0002652 0.0002652] 4.102593644224765e-08 -------------------------------- j:  1467.4606665427418 dj_dw:  -207532.88441333544 dj_db:  -32.08399293287065
[0.00038876 0.00038876 0.00038876 0.00038876 0.00038876] 6.012142816246606e-08 -------------------------------- j:  1433.5554957536426 dj_dw:  -204639.47409447862 dj_db:  -31.615573243839307
[0.0005106 0.0005106 0.0005106 0.0005106 0.0005106] 7.893802773156811e-08 -------------------------------- j:  1400.589142043733 dj_dw:  -201786.40351891957 dj_db:  -31.153684232428514
[0.00063074 0.00063074 0.00063074 0.0

In [70]:
print(w,b)
pred = predict_graph(x_test,per_w,per_b)
print(" Limit","Rating","Cards","Age","Education")
for i in range(test_size):
    print(x_test[i],"       ",round(pred[i],3),y_test[i]) 

# print(pred)



[0. 0. 0. 0. 0.] 0
 Limit Rating Cards Age Education
[4632  355    1   50   17]         46.141 21.786
[3526  289    3   38    7]         35.261 31.335
[4964  365    1   46   13]         49.19 59.855
[4970  352    1   79   11]         49.409 44.061
[7506  536    2   64   13]         74.127 82.706
[1924  165    2   50   14]         19.671 24.46
[3762  287    3   80    8]         37.789 45.12
[3874  298    3   41   14]         38.611 75.406
[4640  332    2   33    6]         45.758 14.956
[7010  494    3   34   18]         68.998 75.257
[4891  369    1   52   16]         48.642 33.694
[5429  396    3   57   15]         53.854 23.375
[5227  386    6   63   11]         51.965 27.825
[7685  534    2   75   18]         75.889 92.386
[9272  656    2   69   14]         91.397 115.52
[3907  296    3   43   16]         38.93 14.479
[7306  522    2   57   14]         72.119 52.179
[4712  340    2   71   16]         46.926 68.462
[1485  129    3   82   13]         15.627 18.951
[2586  229    5   54

In [75]:
def accuracy(x_test,y_test,w,b,):
    pred = predict_graph(x_test,w,b)
    t =np.sum(y_test)
    k = np.sum(pred)
    error = abs(k-t)/t 
    error *= 100
    return error

In [76]:
print(per_w,per_b)

[0.00912788 0.00912788 0.00912788 0.00912788 0.00912788] -3.0639688104570606e-06


In [78]:
print(accuracy(x_test, y_test,per_w,per_b))

3.2100873196976596
