In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl

In [11]:
data = pd.read_csv("./data from book/Credit.csv")
data = data["Limit"]
k = max(data) - min(data)
s =np.array(data)
mean = np.sum(s)/s.shape[0]

for i in range(s.shape[0]):
    data[i] = (data[i] - mean )/ k

feature_scale = data
feature_scale

0     -0.086506
1      0.146225
2      0.179155
3      0.365171
4      0.012360
         ...   
395   -0.048675
396   -0.068739
397   -0.043238
398   -0.169291
399    0.060377
Name: Limit, Length: 400, dtype: float64

In [26]:
data = pd.read_csv("./data from book/Credit.csv")
# data = data[[
# data = np.array(data)

x_data = np.array(data[["Limit","Rating","Cards","Age","Education"]])
y_data = np.array(data["Income"])
# for i in range(x_data.shape[0]):
#     # x_data[i][0] = feature_scale[i]
#     for i in x_data[i]:
#         i *= 0.001
#     y_data[i] *= 0.001

x_test = x_data[300:400]
y_test = y_data[300:400]
x_data = x_data[0:300]
y_data = y_data[0:300]
sample_size = x_data.shape[0]
test_size = x_test.shape[0]

y_data

array([ 14.891, 106.025, 104.593, 148.924,  55.882,  80.18 ,  20.996,
        71.408,  15.125,  71.061,  63.095,  15.045,  80.616,  43.682,
        19.144,  20.089,  53.598,  36.496,  49.57 ,  42.079,  17.7  ,
        37.348,  20.103,  64.027,  10.742,  14.09 ,  42.471,  32.793,
       186.634,  26.813,  34.142,  28.941, 134.181,  31.367,  20.15 ,
        23.35 ,  62.413,  30.007,  11.795,  13.647,  34.95 , 113.659,
        44.158,  36.929,  31.861,  77.38 ,  19.531,  44.646,  44.522,
        43.479,  36.362,  39.705,  44.205,  16.304,  15.333,  32.916,
        57.1  ,  76.273,  10.354,  51.872,  35.51 ,  21.238,  30.682,
        14.132,  32.164,  12.   , 113.829,  11.187,  27.847,  49.502,
        24.889,  58.781,  22.939,  23.989,  16.103,  33.017,  30.622,
        20.936, 110.968,  15.354,  27.369,  53.48 ,  23.672,  19.225,
        43.54 , 152.298,  55.367,  11.741,  15.56 ,  59.53 ,  20.191,
        48.498,  30.733,  16.479,  38.009,  14.084,  14.312,  26.067,
        36.295,  83.

In [13]:
def min__j(x_data,y_data,w,b):
    j= 0
    for i in range(x_data.shape[0]):
        j+=(np.dot(x_data[i],w)+b- (y_data[i]))**2
    ghj = (2*x_data.shape[0])
    return j/ghj

In [14]:

def gradient(x_data,y_data, w, b):
    j_i = 0
    j_j = 0
    m = data.shape[0]
    for i in range(x_data.shape[0]):
        k = (np.dot(x_data[i],w)+b- (y_data[i]))
        j_i += k*np.sum(x_data[i])
        j_j += k
        # if k > 1000000000:
        #     break
    grad = [1/m * j_i, 1/m * j_j]
    return grad

In [15]:
def gradient_descent(x_data,y_data,w,b):
    dist = 0.00000000006
    hist =[]
    count =0
    for i in range(50000):
        count +=1
        dj_dw,dj_db =  gradient(x_data,y_data,w,b)

        w = w-(dist*dj_dw)
        b = b-(dist*dj_db)

        # printing
        if i%10==0:
            print(w,b,"-------------------------------- j: ",min__j(x_data,y_data,w,b),"dj_dw: ",dj_dw,"dj_db: ",dj_db)
        # hist.append([w,b])
        # p =False
        # if len(hist)%5==0:
        #     diff =[]
        #     for k in range(4):
        #         diff.append([abs(hist[k][0]-hist[k+1][0]),abs(hist[k][1]-hist[k+1][1])])
        #     for j in diff:
        #         # print("--------------------------------",diff)
        #         if j[0]<0.00005 and j[1]<0.00005:
        #             p=True
        #         else:
        #             p=False
        #             break
        #     hist = []
        #     diff = []
        # if p==True:
        #     print("breaks",count)
        #     break
    return w,b


In [16]:
def predict_graph(x_data,w,b):
    # pred = np.zeros([x_data.shape[0],])
    pred = np.zeros([x_data.shape[0]])
    for i in range(test_size):
        pred[i] = np.dot(x_data[i],w) +b
    return pred

In [17]:
w = np.zeros([5])
b=0
per_w,per_b = gradient_descent(x_data,y_data,w,b)
print(per_w, per_b)

[1.64966231e-07 1.64966231e-07 1.64966231e-07 1.64966231e-07
 1.64966231e-07] 1.9824477000000004e-09 -------------------------------- j:  1541.8366355270384 dj_dw:  -2749.4371755074985 dj_db:  -33.04079500000001
[1.81462582e-06 1.81462582e-06 1.81462582e-06 1.81462582e-06
 1.81462582e-06] 2.180689223086052e-08 -------------------------------- j:  1541.8305871506573 dj_dw:  -2749.4289536775013 dj_db:  -33.040696608712366
[3.46428048e-06 3.46428048e-06 3.46428048e-06 3.46428048e-06
 3.46428048e-06] 4.1631277727045565e-08 -------------------------------- j:  1541.8245388104513 dj_dw:  -2749.4207318720896 dj_db:  -33.04059821771899
[5.11393021e-06 5.11393021e-06 5.11393021e-06 5.11393021e-06
 5.11393021e-06] 6.145560418873167e-08 -------------------------------- j:  1541.8184905064165 dj_dw:  -2749.4125100912615 dj_db:  -33.04049982701983
[6.763575e-06 6.763575e-06 6.763575e-06 6.763575e-06 6.763575e-06] 8.127987161609535e-08 -------------------------------- j:  1541.812442238557 dj_dw:  -

In [18]:
print(w,b)
pred = predict_graph(x_test,per_w,per_b)
print(" Limit","Rating","Cards","Age","Education")
for i in range(test_size):
    print(x_test[i],"       ",round(pred[i],3),y_test[i]) 

# print(pred)



[0. 0. 0. 0. 0.] 0
 Limit Rating Cards Age Education
[ 4.632  3.55   1.    50.    17.   ]         0.624 21.786
[ 3.526  2.89   3.    38.     7.   ]         0.446 31.335
[ 4.964  3.65   1.    46.    13.   ]         0.562 59.855
[ 4.97  3.52  1.   79.   11.  ]         0.815 44.061
[ 7.506  5.36   2.    64.    13.   ]         0.752 82.706
[ 1.924  1.65   2.    50.    14.   ]         0.57 24.46
[ 3.762  2.87   3.    80.     8.   ]         0.799 45.12
[ 3.874  2.98   3.    41.    14.   ]         0.531 75.406
[ 4.64  3.32  2.   33.    6.  ]         0.401 14.956
[ 7.01  4.94  3.   34.   18.  ]         0.548 75.257
[ 4.891  3.69   1.    52.    16.   ]         0.635 33.694
[ 5.429  3.96   3.    57.    15.   ]         0.691 23.375
[ 5.227  3.86   6.    63.    11.   ]         0.729 27.825
[ 7.685  5.34   2.    75.    18.   ]         0.884 92.386
[ 9.272  6.56   2.    69.    14.   ]         0.826 115.52
[ 3.907  2.96   3.    43.    16.   ]         0.564 14.479
[ 7.306  5.22   2.    57.    14.   ] 

In [19]:
def accuracy(x_test,y_test,w,b,):
    pred = predict_graph(x_test,w,b)
    t =np.sum(y_test)
    k = np.sum(pred)
    error = abs(k-t)/t 
    error *= 100
    return error

In [20]:
print(per_w,per_b)

[0.00818696 0.00818696 0.00818696 0.00818696 0.00818696] 9.838812801790695e-05


In [21]:
print(accuracy(x_test, y_test,per_w,per_b))

98.60647686162469
