In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl

In [44]:
data = pd.read_csv("./data from book/Credit.csv")
data = data["Limit"]
k = max(data) - min(data)
s =np.array(data)
mean = np.sum(s)/s.shape[0]

for i in range(s.shape[0]):
    data[i] = (data[i] - mean )/ k

feature_scale = data
feature_scale

0     -0.086506
1      0.146225
2      0.179155
3      0.365171
4      0.012360
         ...   
395   -0.048675
396   -0.068739
397   -0.043238
398   -0.169291
399    0.060377
Name: Limit, Length: 400, dtype: float64

In [45]:
data = pd.read_csv("./data from book/Credit.csv")
# data = data[[
# data = np.array(data)

x_data = np.array(data[["Limit","Rating","Cards","Age","Education"]])
# for i in range(x_data.shape[0]):
#     x_data[i][0] = feature_scale[i]
y_data = np.array(data["Income"])
x_test = x_data[300:400]
y_test = y_data[300:400]
x_data = x_data[0:300]
y_data = y_data[0:300]
sample_size = x_data.shape[0]
test_size = x_test.shape[0]

x_data

array([[3606,  283,    2,   34,   11],
       [6645,  483,    3,   82,   15],
       [7075,  514,    4,   71,   11],
       ...,
       [4381,  321,    3,   74,   17],
       [2672,  204,    1,   70,   18],
       [5051,  372,    3,   76,   11]], dtype=int64)

In [46]:
def min__j(x_data,y_data,w,b):
    j= 0
    for i in range(x_data.shape[0]):
        j+=(np.dot(x_data[i],w)+b- (y_data[i]))**2
    ghj = (2*x_data.shape[0])
    return j/ghj

In [47]:

def gradient(x_data,y_data, w, b):
    j_i = np.zeros(w.shape[0])
    j_j = 0
    m = data.shape[0]
    for i in range(x_data.shape[0]):
        k = (np.dot(x_data[i],w)+b- (y_data[i]))
        for gb in range(w.shape[0]): 
            j_i[gb] += (k*x_data[i][gb])
        
        j_j += k
        # if k > 1000000000:
        #     break
    grad = [1/m * j_i, 1/m * j_j]
    return grad

In [48]:
def gradient_descent(x_data,y_data,w,b):
    dist = 0.00000000006
    hist =[]
    count =0
    for i in range(50000):
        count +=1
        dj_dw,dj_db =  gradient(x_data,y_data,w,b)

        # print(dj_dw,dj_db)
        # for gb in range(dj_dw.shape[0]):
        w = w-(dist*dj_dw)
        b = b-(dist*dj_db)

        # printing
        if i%10==0:
            print(w,b,"-------------------------------- j: ",min__j(x_data,y_data,w,b),"dj_dw: ",dj_dw,"dj_db: ",dj_db)
        # hist.append([w,b])
        # p =False
        # if len(hist)%5==0:
        #     diff =[]
        #     for k in range(4):
        #         diff.append([abs(hist[k][0]-hist[k+1][0]),abs(hist[k][1]-hist[k+1][1])])
        #     for j in diff:
        #         # print("--------------------------------",diff)
        #         if j[0]<0.00005 and j[1]<0.00005:
        #             p=True
        #         else:
        #             p=False
        #             break
        #     hist = []
        #     diff = []
        # if p==True:
        #     print("breaks",count)
        #     break
    return w,b


In [49]:
def predict_graph(x_data,w,b):
    # pred = np.zeros([x_data.shape[0],])
    pred = np.zeros([x_data.shape[0]])
    for i in range(test_size):
        pred[i] = np.dot(x_data[i],w) +b
    return pred

In [50]:
w = np.zeros([5])
b=0
per_w,per_b = gradient_descent(x_data,y_data,w,b)
print(per_w, per_b)

[1.17952517e-05 8.66826419e-07 6.05945715e-09 1.12223088e-07
 2.62201698e-08] 1.9824477000000004e-09 -------------------------------- j:  1538.73037267645 dj_dw:  [-1.96587528e+05 -1.44471070e+04 -1.00990953e+02 -1.87038479e+03
 -4.37002830e+02] dj_db:  -33.04079500000001
[1.28974935e-04 9.47814508e-06 6.62397042e-08 1.22696820e-06
 2.86626930e-07] 2.1671542154927147e-08 -------------------------------- j:  1508.067135159487 dj_dw:  [-1.94249802e+05 -1.42748539e+04 -9.97376729e+01 -1.84774128e+03
 -4.31573369e+02] dj_db:  -32.63127971636185
[2.44761173e-04 1.79867891e-05 1.25672911e-07 2.32821622e-06
 5.43797359e-07] 4.111653737208693e-08 -------------------------------- j:  1478.128838638134 dj_dw:  [-1.91939876e+05 -1.41046492e+04 -9.84992969e+01 -1.82536704e+03
 -4.26208473e+02] dj_db:  -32.22663427713606
[3.59170536e-04 2.63939794e-05 1.84367960e-07 3.41612765e-06
 7.97769942e-07] 6.032033611326219e-08 -------------------------------- j:  1448.8983440386728 dj_dw:  [-1.89657419e+05

In [51]:
print(w,b)
pred = predict_graph(x_test,per_w,per_b)
print(" Limit","Rating","Cards","Age","Education")
for i in range(test_size):
    print(x_test[i],"       ",round(pred[i],3),y_test[i]) 

# print(pred)



[0. 0. 0. 0. 0.] 0
 Limit Rating Cards Age Education
[4632  355    1   50   17]         45.958 21.786
[3526  289    3   38    7]         34.996 31.335
[4964  365    1   46   13]         49.243 59.855
[4970  352    1   79   11]         49.294 44.061
[7506  536    2   64   13]         74.45 82.706
[1924  165    2   50   14]         19.1 24.46
[3762  287    3   80    8]         37.325 45.12
[3874  298    3   41   14]         38.438 75.406
[4640  332    2   33    6]         46.023 14.956
[7010  494    3   34   18]         69.526 75.257
[4891  369    1   52   16]         48.524 33.694
[5429  396    3   57   15]         53.853 23.375
[5227  386    6   63   11]         51.853 27.825
[7685  534    2   75   18]         76.216 92.386
[9272  656    2   69   14]         91.963 115.52
[3907  296    3   43   16]         38.762 14.479
[7306  522    2   57   14]         72.466 52.179
[4712  340    2   71   16]         46.739 68.462
[1485  129    3   82   13]         14.743 18.951
[2586  229    5   54 

In [52]:
def accuracy(x_test,y_test,w,b,):
    pred = predict_graph(x_test,w,b)
    t =np.sum(y_test)
    k = np.sum(pred)
    error = abs(k-t)/t 
    error *= 100
    return error

In [53]:
print(per_w,per_b)

[ 9.87504480e-03  6.12966027e-04 -7.90342894e-06 -5.55959083e-06
 -3.57728322e-05] -2.458263761587744e-06


In [54]:
print(accuracy(x_test, y_test,per_w,per_b))

3.016768440433246
