In [2]:
import numpy as np
import matplotlib.pyplot as pl
import random
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [3]:
k  = tf.constant([[1,2,3],[1,6,2]])
g  = tf.constant([2,3,2,32,13,2,242,4])
v = tf.constant([123,0,5])
v = tf.reshape(v,[-1,1])

print(tf.linalg.matmul(k,v))

tf.Tensor(
[[138]
 [133]], shape=(2, 1), dtype=int32)


In [4]:
x = tf.constant([[1,2,3],[1,2,3],[1,2,3]])
# y = tf.constant([[1,3,4],[2,3,4],[3,3,4]])
# x = np.array([[1,2,3],[1,2,3],[1,2,3]])
y = np.array([[1,3,4],[2,3,4    ],[3,3,4]])
print(x*y)

tf.Tensor(
[[ 1  6 12]
 [ 2  6 12]
 [ 3  6 12]], shape=(3, 3), dtype=int32)


In [13]:
t=tf.constant([[1,2,2,32,1323,213],[1,2,2,32,13,69213]])
t[-1]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([    1,     2,     2,    32,    13, 69213])>

In [8]:
np.array([[1,2,2,32,1323,213],[1,2,2,32,1323,213]])

array([[   1,    2,    2,   32, 1323,  213],
       [   1,    2,    2,   32, 1323,  213]])